version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  flask:
    build:
      context: .
      dockerfile: Dockerfile_flask
    ports:
      - "5000:5000"
